name: Swift Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"  # using Swift 6 locally, but github is at 5.9

    - name: Build project
      run: swift build

    - name: Run tests
      run: swift test
